import type { Metadata } from "next";
import "@/app/globals.css";
import { IntlProvider } from 'react-intl';
import locale from '@/locales/pt.json';
import { AuthProvider } from "@/contexts/auth-context";

export const metadata: Metadata = {
  title: "SaaS Multi-Tenant Base",
  description: "Generated by SaaS Multi-Tenant Base",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="--font-inter h-full antialiased">
      <IntlProvider locale="pt-BR" messages={locale}>
        <body className="min-h-full flex flex-col">
          <AuthProvider>{children}</AuthProvider>
        </body>
      </IntlProvider>
    </html>
  );
}
