export const TenantErrorCode = {
    DUPLICATE: 'TENANT_DUPLICATE',
    NOT_FOUND: 'TENANT_NOT_FOUND',
    ID_INVALID: 'TENANT_ID_INVALID',
    DATE_RANGE_INVALID: 'TENANT_DATE_RANGE_INVALID',
    CREATE_ERROR: 'TENANT_CREATE_ERROR',
    FIND_ALL_ERROR: 'TENANT_FINDALL_ERROR',
    FIND_ONE_ERROR: 'TENANT_FINDONE_ERROR',
    UPDATE_ERROR: 'TENANT_UPDATE_ERROR',
    REMOVE_ERROR: 'TENANT_REMOVE_ERROR',
    REMOVED: 'TENANT_REMOVED',
} as const;
